#ifndef MS449_TESTING
#define MS449_TESTING

#include <iostream>
#include <string>
#include <vector>
#include <functional>

namespace unit_testing {
	using namespace std;

	/// <summary>
	/// A implimentation of a basic unit testing framework.
	/// </summary>
	class UnitTest {
	public:
		/// <summary>
		/// A object representing the result of a unit test. 
		/// </summary>
		class TestResult {
		public:
			/// <summary>
			/// Name of the test which the result was generated by.
			/// </summary>
			string name;

			/// <summary>
			/// If the test passed.
			/// </summary>
			bool passed;

			/// <summary>
			/// Create an instance of TestResult
			/// </summary>
			/// <param name="name">Name of the test generating the result.</param>
			/// <param name="passed">If the test passed.</param>
			TestResult(string name, bool passed) {
				this->name = name;
				this->passed = passed;
			}
		};

	private:
		/// <summary>
		/// Name of the UnitTest instance.
		/// </summary>
		string name;

		/// <summary>
		/// Vector containing results of the UnitTest instance.
		/// </summary>
		vector<TestResult> results;

		/// <summary>
		/// The stream to which logs are sent.
		/// </summary>
		ostream & log_stream;

	public:
		/// <summary>
		/// Construct and instance of unit test with a given name.
		/// </summary>
		/// <param name="name">Name of the UnitTest instance.</param>
		UnitTest(string name = "Unit Test", ostream& log_stream = cout) {
			this->name = name;
			this->log_stream = log_stream;
		}

		/// <summary>
		/// Log a value to the specified loging stream given a optional test name.
		/// </summary>
		/// <param name="message">Message to be logged.</param>
		/// <param name="testName">Name of the test log is sent from (if applicalbe)</param>
		void log(string message, string testName = "") {
			cout << "[" << this->name << "]" << (testName.empty() ? "" : ("(" + testName + ")")) << ": " << message << endl;
		}

		/// <summary>
		/// Log the result of a test.
		/// </summary>
		void log_result(string testName, bool testPassed) {
			results.push_back(TestResult(name, testPassed));
		}

		/// <summary>
		/// Assert that the first value provided is the same as the second expected value.
		/// </summary>
		/// <typeparam name="T">Type of the value being compared.</typeparam>
		/// <param name="name">Name of the test being performed.</param>
		/// <param name="value">Value being compared to the expected value.</param>
		/// <param name="expected">What the value provided is expected to be.</param>
		template <typename T> void assert(string name, T value, T expected) {
			this->log_result(name, value == expected);
		}

		/// <summary>
		/// Run a test asserting that the value return by the provided function is equal to the expected value.
		/// </summary>
		/// <typeparam name="T">Type of the value being compared.</typeparam>
		/// <param name="name">Name of the test being performed.</param>
		/// <param name="func">Function which returns a value.</param>
		/// <param name="expected">What the value returned by the function is expected to be.</param>
		template <typename T> void ASSERT(string name, function<T()> func, T expected) {
			try {
				//run the function and get the result
				T result = func();
				
				//log the result
				this->log_result(name, result == expected);
			}
			catch (const std::exception& e) {
				this->LOG("Unhandled Exception: " + *e.what(), name);
				results.push_back(TestResult("[EXCEPTION]" + name, false));
			}
		}

		/// <summary>
		/// Checks all performed tests to see if any failed, if all passed true is returned, otherwise false.
		/// </summary>
		/// <returns>If all tests passed.</returns>
		bool TEST_PASSED() {
			for (auto result : this->results) {
				if (!result.passed) return false;
			}

			return true;
		}
		
		/// <summary>
		/// Log the results of the unit test to the specified stream.
		/// </summary>
		void LOG_RESULTS(ostream& stream = cout) {
			stream << "+-" << string(this->name.length(), '-') << "---------+" << endl;
			stream << "| " << this->name						 << " Results |" << endl;
			stream << "+-" << string(this->name.length(), '-') << "---------+" << endl;
			stream << endl;
				
			for (int i = 0; i < this->results.size(); i++) {
				auto result = this->results[i];
				stream << "[#" << (i + 1) << ")[" << (result.passed ? "PASSED" : "FAILED") << "]: " << result.name << endl << endl;
			}

			//get number of tests
			int totalTests = this->results.size();
			int totalPassedTests = 0;

			for (auto result : this->results) {
				if (result.passed) totalPassedTests += 1;
			}

			stream << "|\\" << endl;
			stream << "|| <> RESULT <>" << endl;
			stream << "|| - " << (this->TEST_PASSED() ? "TEST PASSED" : "TEST FAILED") << endl;
			stream << "|| - " << totalPassedTests << "/" << totalTests << " Tests Passed" << endl;
			stream << "|/" << endl;
		}
	};
}

#endif